env: dev
paper: true
live : false
api: 
  key: null
  secret: null
strategy:
  name: macd
  params:
    fast: 5
    slow: 9
    signal: 3
    use_crossover: false
    cooldown: 0
    qty: 10000
  symbols: ["KRW-BTC"]
data:
  interval: "1m"
  window: 60
#   csv: "data/BTCUSDT_1m.csv"
exchange:
  name: upbit
  base_url: "https://api.upbit.com/v1"
risk:
  max_orders: 5
  min_qty: 0.0001
  max_daily_loss: 0.05       # -5% 이상 손실 시 중단
  max_unrealized_loss: 0.1   # -10% 미실현 손실 제한
  cooldown_s: 2
