env: dev
paper: true
api: 
  key: null
  secret: null
strategy:
  name: sma_cross
  params:
    fast: 5
    slow: 10
  symbols:
    - "BTC/USDT"
data:
  interval: "1m"
  window: 60
#   csv: "data/BTCUSDT_1m.csv"
risk: {}
exchange:
  name: upbit
  base_url: "https://api.upbit.com/v1"
paper: true
live: false
