env: dev
paper: true
api: { key: null, secret: null }
strategy:
  name: bbands
  params: { window: 20, k: 2.0, mode: "breakout", use_crossover: true, cooldown: 3, qty: 0.001 }
  symbols: ["BTC/USDT"]
data: { interval: "1m", window: 60 }
risk: {}
