name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    name: pytest (${{ matrix.os }} / py${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python }}-

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          # 만약 dev extras가 없다면:
          pip install pytest pytest-cov typer[all] mypy ruff

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy src

      - name: Test (pytest + coverage)
        run: |
          pytest -q --cov=src/autotrade --cov-report=xml --cov-report=term
        shell: bash

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}-py${{ matrix.python }}
          path: coverage.xml